WebsitePhanPhoiSach/Models/danhmucsachdaban.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsitePhanPhoiSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class danhmucsachdaban
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public danhmucsachdaban()
        {
            this.ctdmsdbs = new HashSet<ctdmsdb>();
        }
    
        public int iddmsdb { get; set; }
        public Nullable<int> iddl { get; set; }
        public Nullable<System.DateTime> thoigian { get; set; }
        public Nullable<decimal> sotiendathanhtoan { get; set; }
        public Nullable<decimal> sotienconno { get; set; }
        public string tinhtrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ctdmsdb> ctdmsdbs { get; set; }
        public virtual daily daily { get; set; }
    }
}

WebsitePhanPhoiSach/Models/danhmucsachdabanviewmodel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebsitePhanPhoiSach.Models
{
    public class danhmucsachdabanviewmodel
    {
        public danhmucsachdaban danhmucsachdaban
            { get;
            set;
        }
        public ctdmsdb ctdmsdb
        {
            get;
            set;
        }
    }
}

WebsitePhanPhoiSach/Controllers/danhmucsachdabansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebsitePhanPhoiSach.Models;

namespace WebsitePhanPhoiSach.Controllers
{
    public class danhmucsachdabansController : Controller
    {
        private ctyppsachEntities db = new ctyppsachEntities();

        
        // GET: danhmucsachdabans
        public ActionResult Index()
        {
            var danhmucsachdaban = db.danhmucsachdabans.Include(d => d.daily);
            return View(danhmucsachdaban.ToList());
        }
        [HttpPost]
        public ActionResult Index(string iddmsdb)
        {
            int id;
            if (int.TryParse(iddmsdb, out id))
            {
                edittratien(id);
            }
            var danhmucsachdaban = db.danhmucsachdabans.Include(d => d.daily);
            return View(danhmucsachdaban.ToList());
        }

        // GET: danhmucsachdabans/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            danhmucsachdaban danhmucsachdaban = db.danhmucsachdabans.Find(id);
            if (danhmucsachdaban == null)
            {
                return HttpNotFound();
            }
            return View(danhmucsachdaban);
        }

        // GET: danhmucsachdabans/Create
        public ActionResult Create()
        {
            ViewBag.iddl = new SelectList(db.dailies, "iddl", "tendl");
            ViewBag.idsach = new SelectList(db.saches, "idsach", "tensach");
            return View();
        }

        // POST: danhmucsachdabans/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Prefix = "danhmucsachdaban")] danhmucsachdaban danhmucsachdaban,
                                    [Bind(Prefix = "ct")] ctdmsdb[] ctdmsdb)
        {
            danhmucsachdabanviewmodel dmvm = new danhmucsachdabanviewmodel();
            if (ModelState.IsValid)
            {
                danhmucsachdaban.tinhtrang = "Waiting";
                danhmucsachdaban.sotiendathanhtoan = 0;
                decimal tongtien = 0;
                decimal tongtienbanduoc = 0;
                int iddm = 1;
                if(db.danhmucsachdabans.Any())
                iddm = db.danhmucsachdabans.Max(a => a.iddmsdb) + 1;
                int idct = 1;
                foreach(ctdmsdb ct in ctdmsdb)
                {
                    ct.iddmsdb = iddm;
                    ct.idctdmsdb = idct;
                    idct++;
                    hangtoncuadaily htdl = db.hangtoncuadailies.FirstOrDefault(o => o.iddl == danhmucsachdaban.iddl && o.idsach == ct.idsach);
                    if(htdl == null )
                    {
                        ModelState.AddModelError("", "Không tìm thấy hàng tồn . Chọn sai đại lý hoặc là chọn sai tên sách ở chi tiết");
                        ViewBag.iddl = new SelectList(db.dailies, "iddl", "tendl", danhmucsachdaban.iddl);
                        ViewBag.idsach = new SelectList(db.saches, "idsach", "tensach");
                        dmvm.danhmucsachdaban = danhmucsachdaban;
                        return View(dmvm);
                    }
                  
                    if (htdl != null && htdl.soluongchuaban >= ct.soluong)
                    {
                        htdl.soluongchuaban = htdl.soluongchuaban - ct.soluong;
                        db.Entry(htdl).State = EntityState.Modified;
                    }
                        else
                    {
                        ModelState.AddModelError("", "Số lượng sách đã bán lớn hơn số sách xuất cho đại lý");
                        ViewBag.iddl = new SelectList(db.dailies, "iddl", "tendl", danhmucsachdaban.iddl);
                        ViewBag.idsach = new SelectList(db.saches, "idsach", "tensach");
                        dmvm.danhmucsachdaban = danhmucsachdaban;
                        return View(dmvm);
                    }
                    tongtien += (decimal)(ct.soluong * db.saches.Find(ct.idsach).giaxuat);
                    //cập nhật số tiền phải tra cho nhà xuất bản 
                    sach s = db.saches.Find(ct.idsach);
                    System.Diagnostics.Debug.WriteLine("Id sách " + ct.idsach);
                    nxb n = db.nxbs.Find(s.idnxb);
                    System.Diagnostics.Debug.WriteLine("Id nhà xuất bản : " + n.idnxb);
                    System.Diagnostics.Debug.WriteLine("Nhà xuất bản : "+n.tennxb);
                    sotienphaitrachonxb st = new sotienphaitrachonxb();
                    st.thoidiem = (DateTime)danhmucsachdaban.thoigian;
                    sotienphaitrachonxb stht = db.sotienphaitrachonxbs.OrderByDescending(o => o.id).FirstOrDefault(o => o.idnxb == n.idnxb);
                    System.Diagnostics.Debug.WriteLine("Id nhà xuất bản sau khi lấy : " + stht.idnxb);

                    System.Diagnostics.Debug.WriteLine("Số tiền phải trả cho nhà xuất bản : " + stht.sotienphaitra);

                    tongtienbanduoc = (decimal)(ct.soluong * s.gianhap);
                    System.Diagnostics.Debug.WriteLine(tongtienbanduoc);
                    if (stht != null)
                        {
                        st.idnxb = n.idnxb;
                        st.sotienphaitra = (ct.soluong * s.gianhap);
                        System.Diagnostics.Debug.WriteLine("Đây là số tiền phải trả : " +
                            st.sotienphaitra);
                        db.sotienphaitrachonxbs.Add(st);
                    }
                    else
                    {
                        ModelState.AddModelError("", "Không lấy được số tiền phải trả cho nhà xuất bản");
                        ViewBag.iddl = new SelectList(db.dailies, "iddl", "tendl", danhmucsachdaban.iddl);
                        ViewBag.idsach = new SelectList(db.saches, "idsach", "tensach");
                        dmvm.danhmucsachdaban = danhmucsachdaban;
                        return View(dmvm);
                    }
                }
                /*congnotheothoigian cn = new congnotheothoigian();
                cn.thoidiem = (DateTime)danhmucsachdaban.thoigian;
                congnotheothoigian cnht = db.congnotheothoigians.OrderByDescending(o => o.id).FirstOrDefault(o => o.iddl == danhmucsachdaban.iddl);
                if(cnht.congno!=null)
                {
                    cn.iddl = danhmucsachdaban.iddl;
                    cn.congno = cnht.congno - tongtien;
                    db.congnotheothoigians.Add(cn);
                }
                else
                {
                    cn.iddl = danhmucsachdaban.iddl;
                    cn.congno = tongtien;
                    db.congnotheothoigians.Add(cn);
                }
               */
                danhmucsachdaban.sotienconno = tongtien;
                danhmucsachdaban.ctdmsdbs = ctdmsdb;
                db.danhmucsachdabans.Add(danhmucsachdaban);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.iddl = new SelectList(db.dailies, "iddl", "tendl", danhmucsachdaban.iddl);
            ViewBag.idsach = new SelectList(db.saches, "idsach", "tensach");
            dmvm.danhmucsachdaban = danhmucsachdaban;
            return View(dmvm);
        }

        // GET: danhmucsachdabans/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            danhmucsachdaban danhmucsachdaban = db.danhmucsachdabans.Find(id);
            if (danhmucsachdaban == null)
            {
                return HttpNotFound();
            }
            ViewBag.idsach = new SelectList(db.saches, "idsach", "tensach");
            danhmucsachdabanviewmodel dmvm = new danhmucsachdabanviewmodel();

            ViewBag.iddl = new SelectList(db.dailies, "iddl", "tendl", danhmucsachdaban.iddl);
            dmvm.danhmucsachdaban = danhmucsachdaban;
            return View(dmvm);
        }

        // POST: danhmucsachdabans/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Prefix = "danhmucsachdaban")] danhmucsachdaban danhmucsachdaban,
                                 [Bind(Prefix = "ct")] ctdmsdb[] ctdmsdb)
        {
            ViewBag.iddl = new SelectList(db.dailies, "iddl", "tendl", danhmucsachdaban.iddl);
            ViewBag.idsach = new SelectList(db.saches, "idsach", "tensach");
            danhmucsachdabanviewmodel dmvm = new danhmucsachdabanviewmodel();

            if (ModelState.IsValid)
            {
                decimal tongtien = 0;
                decimal tongtienmoi = 0;
                int iddmsdb = danhmucsachdaban.iddmsdb;
                int idct = 1;
                //xoa chi tiet cu trong database table hangtoncuadaily
                var ctcudmsdb = db.ctdmsdbs.Where(o => o.iddmsdb == danhmucsachdaban.iddmsdb);
                foreach (ctdmsdb ct in ctcudmsdb)
                {
                    hangtoncuadaily ht = db.hangtoncuadailies.FirstOrDefault(o => o.iddl == danhmucsachdaban.iddl && o.idsach == ct.idsach);
                    int hangtondaily = (int)(ht.soluongchuaban + ct.soluong);
                    ht.soluongchuaban = hangtondaily;
                    db.Entry(ht).State = EntityState.Modified;
                    System.Diagnostics.Debug.WriteLine("Hàng tồn đại lý return : " + hangtondaily);

WebsitePhanPhoiSach/Views/danhmucsachdabans/Create.cshtml
@model WebsitePhanPhoiSach.Models.danhmucsachdabanviewmodel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Thêm</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Báo cáo đại lý</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("ID Đại lý", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("danhmucsachdaban.iddl", ViewBag.iddl as SelectList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.danhmucsachdaban.iddl, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Thời gian", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.danhmucsachdaban.thoigian, new { htmlAttributes = new { @class = "datepicker form-control", autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.danhmucsachdaban.thoigian, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-inline">
        <h4>Thêm chi tiết vào báo cáo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.LabelFor(model => model.ctdmsdb.idsach, "Tên sách")
        <div class="form-group">
            @Html.DropDownList("idsach", null, htmlAttributes: new { @class = "form-control", @id = "item" })
            @Html.ValidationMessageFor(model => model.ctdmsdb.idsach, "", new { @class = "text-danger" })
        </div>
        @Html.LabelFor(model => model.ctdmsdb.soluong, "Số lượng")
        <div class="form-group">
            @Html.EditorFor(model => model.ctdmsdb.soluong, new { htmlAttributes = new { @class = "form-control", @id = "amount" } })
            @Html.ValidationMessageFor(model => model.ctdmsdb.soluong, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            <input type="button" id="btnAdd" class="btn btn-default" value="Add" />
        </div>
    </div>

    <hr />
    <table class="table" id="chitiet">
        <tr>
            <td>ID</td>
            <td>ID Sách</td>
            <td>Tên Sách</td>
            <td>Số lượng đã bán</td>
            <td></td>
        </tr>
        @if (Model != null)
        {
            foreach (var ct in Model.danhmucsachdaban.ctdmsdbs)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => ct.idctdmsdb)</td>
                    <td>@Html.DisplayFor(modelItem => ct.idsach)</td>
                    <td>@Html.DisplayFor(modelItem => ct.sach.tensach)</td>
                    <td>@Html.DisplayFor(modelItem => ct.soluong)</td>
                    <td><button class="btn btn-danger btnDelete">Delete</button></td>
                    @Html.Hidden("ct.Index", ct.idctdmsdb)
                    @Html.Hidden("ct[" + ct.idctdmsdb + "].idsach", ct.idsach)
                    @Html.Hidden("ct[" + ct.idctdmsdb + "].soluong", ct.soluong)
                </tr>
            }
        }
    </table>
    <hr />
    <div class="form-group">
        <input type="submit" value="Thêm" class="btn btn-default" />
    </div>
}
<div>
    @Html.ActionLink("Trở về trang danh sách", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/mycustomjquery")
}

WebsitePhanPhoiSach/Views/danhmucsachdabans/Delete.cshtml
@model WebsitePhanPhoiSach.Models.danhmucsachdaban

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>danhmucsachdaban</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.thoigian)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.thoigian)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sotiendathanhtoan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sotiendathanhtoan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sotienconno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sotienconno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.daily.tendl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.daily.tendl)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebsitePhanPhoiSach/Views/danhmucsachdabans/Details.cshtml
@model WebsitePhanPhoiSach.Models.danhmucsachdaban

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Chi tiết báo cáo</h2>

<div>
    <h4>Báo cáo đại lý</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>        
            @Html.DisplayName("Ngày tạo báo cáo")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.thoigian)
        </dd>

        <dt>
            @Html.DisplayName("Số tiền đại lý đã thanh toán")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sotiendathanhtoan)
        </dd>

        <dt>
            @Html.DisplayName("Số tiền đại lý còn nợ")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sotienconno)
        </dd>

        <dt>
            @Html.DisplayName("Tên đại lý")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.daily.tendl)
        </dd>

    </dl>
</div>
<table class="table">
    <tr>
        <th>@Html.DisplayName("Tên Sách")</th>
        <th>@Html.DisplayName("Số lượng báo cáo ")</th>
        <th></th>
    </tr>
    @if (Model.ctdmsdbs != null)
    {
        foreach (var item in Model.ctdmsdbs)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.sach.tensach)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.soluong)
                </td>
            </tr>

        }
    }
    else
    {
        <tr>
            <td>Không có chi tiết</td>
        </tr>
    }
</table>
<p>
  
    @Html.ActionLink("Trở về trang danh sách", "Index")
</p>

WebsitePhanPhoiSach/Views/danhmucsachdabans/Edit.cshtml
@model WebsitePhanPhoiSach.Models.danhmucsachdabanviewmodel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Sửa</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Báo cáo đại lý</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(o => o.danhmucsachdaban.iddmsdb)
        <div class="form-group">
            @Html.Label("ID Đại lý", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("danhmucsachdaban.iddl", ViewBag.iddl as SelectList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.danhmucsachdaban.iddl, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Thời gian", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.danhmucsachdaban.thoigian, new { htmlAttributes = new { @class = "datepicker form-control", autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.danhmucsachdaban.thoigian, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-inline">
        <h4>Thêm chi tiết vào báo cáo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.LabelFor(model => model.ctdmsdb.idsach, "Tên sách")
        <div class="form-group">
            @Html.DropDownList("idsach", null, htmlAttributes: new { @class = "form-control", @id = "item" })
            @Html.ValidationMessageFor(model => model.ctdmsdb.idsach, "", new { @class = "text-danger" })
        </div>
        @Html.LabelFor(model => model.ctdmsdb.soluong, "Số lượng")
        <div class="form-group">
            @Html.EditorFor(model => model.ctdmsdb.soluong, new { htmlAttributes = new { @class = "form-control", @id = "amount" } })
            @Html.ValidationMessageFor(model => model.ctdmsdb.soluong, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            <input type="button" id="btnAdd" class="btn btn-default" value="Add" />
        </div>
    </div>

    <hr />
    <table class="table" id="chitiet">
        <tr>
            <td>ID</td>
            <td>ID Sách</td>
            <td>Tên Sách</td>
            <td>Số lượng đã bán</td>
            <td></td>
        </tr>
        @if (Model != null)
        {
            foreach (var ct in Model.danhmucsachdaban.ctdmsdbs)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => ct.idctdmsdb)</td>
                    <td>@Html.DisplayFor(modelItem => ct.idsach)</td>
                    <td>@Html.DisplayFor(modelItem => ct.sach.tensach)</td>
                    <td>@Html.DisplayFor(modelItem => ct.soluong)</td>
                    <td><button class="btn btn-danger btnDelete">Delete</button></td>
                    @Html.Hidden("ct.Index", "a" + ct.idctdmsdb)
                    @Html.Hidden("ct[" + "a" + ct.idctdmsdb + "].idsach", ct.idsach)
                    @Html.Hidden("ct[" + "a" + ct.idctdmsdb + "].soluong", ct.soluong)
                </tr>
            }
        }
    </table>
    <hr />

    <div class="form-group">
        <input type="submit" value="Lưu" class="btn btn-default" />
    </div>

}
<div>
    @Html.ActionLink("Trở về trang danh sách", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/mycustomjquery")
}

WebsitePhanPhoiSach/Views/danhmucsachdabans/Index.cshtml
@model IEnumerable<WebsitePhanPhoiSach.Models.danhmucsachdaban>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Các báo cáo đại lý</h2>
<p>
    @Html.ActionLink("Thêm mới", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Thời gian
        </th>
        <th>
            Tên đại lý
        </th>
        <th>
            Số tiền còn nợ
        </th>
        <th>
            Số tiền đã thanh toán
        </th>
        <th>
            Tình trạng
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.thoigian)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.daily.tendl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.sotienconno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.sotiendathanhtoan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tinhtrang)
            </td>
            <td>
                @if (item.tinhtrang == "Waiting")
                {@Html.ActionLink("Sửa", "Edit", new { id = item.iddmsdb })  } |
                @Html.ActionLink("Chi tiết báo cáo", "Details", new { id = item.iddmsdb })
                
               
                @using (Html.BeginForm("Index", "danhmucsachdabans", FormMethod.Post))
                {
                    @Html.Hidden("iddmsdb", item.iddmsdb)
                    if (item.tinhtrang == "Waiting")
                    {
                        <input type="submit" value="Thanh toán" class="btn btn-default" />
                        }
                    }
                
            </td>
        </tr>
    }
</table>