WebsitePhanPhoiSach/Controllers/tonkhoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebsitePhanPhoiSach.Models;


namespace WebsitePhanPhoiSach.Controllers
{
    public class tonkhoesController : Controller
    {
        private ctyppsachEntities db = new ctyppsachEntities();

        // GET: tonkhoes
        public ActionResult Index(string thoidiem)
        {
            
            DateTime searchDate;
            if (DateTime.TryParse(thoidiem, out searchDate))
            {
                
                List<tonkho> tks = new List<tonkho>();
                DateTime tomorrowdate = searchDate.AddDays(1);
                var tonkhoes = db.tonkhoes.Include(c => c.sach)
                    .OrderByDescending(o => o.idtk)
                    .FirstOrDefault(h => h.thoidiem <= tomorrowdate);
                
                tks.Add(tonkhoes);
               
                return View(tks);
                // do not use .Equals() which can not be converted to SQL
            }
        

            var tonkho = db.tonkhoes.Include(t => t.sach);
            return View(tonkho.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebsitePhanPhoiSach/Views/tonkhoes/Index.cshtml
@model IEnumerable<WebsitePhanPhoiSach.Models.tonkho>
@{
    ViewBag.Title = "Index";
}
<h2>Tồn Kho</h2>
@using (Html.BeginForm("Index", "tonkhoes", FormMethod.Get))
{
    <div class="form-inline">
        @Html.Label("Thời điểm")
        <div class="form-group input-group-sm">
            @Html.TextBox("thoidiem", null, new { @class = "form-control datepicker", placeholder = "Chọn ngày tháng năm", autocomplete = "off" })
        </div>
        @*<input type="date" class="form-control"/>*@
        <div class="form-group">
            <div>
                <input type="submit" value="Tìm" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<hr />
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Thời điểm cập nhật")
        </th>
        <th>
            @Html.DisplayName("Số lượng tồn")
        </th>
     
        <th>
            @Html.DisplayName("Tên Sách")
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.thoidiem)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.soluongton)
            </td>
         
            <td>
                @Html.DisplayFor(modelItem => item.sach.tensach)
            </td>
        </tr>
    }
</table>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/mycustomjquery")
}