WebsitePhanPhoiSach/Models/doanhthuviewmodel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebsitePhanPhoiSach.Models
{
    public class doanhthuviewmodel
    {
        public List<chitietdoanhthu> ctdt { get; set; }
        public decimal doanhthu { get; set; }
        public DateTime startdate { get; set; }
        public DateTime enddate { get; set; }
    }
}

WebsitePhanPhoiSach/Controllers/doanhthuController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebsitePhanPhoiSach.Models;

namespace WebsitePhanPhoiSach.Controllers
{
    public class doanhthuController : Controller
    {
        private ctyppsachEntities db = new ctyppsachEntities();

        // GET: doanhthu
        public ActionResult Index(string tungay, string denngay)
        {
            doanhthuviewmodel dtvm = new doanhthuviewmodel();
            DateTime startdate, enddate;
            if (DateTime.TryParse(tungay, out startdate) && DateTime.TryParse(denngay, out enddate))
            {
                dtvm.startdate = startdate;
                dtvm.enddate = enddate;
                dtvm.ctdt = db.ctdmsdbs
                            .Include(c => c.danhmucsachdaban)
                            .Include(c => c.sach)
                            .Where(o => o.danhmucsachdaban.thoigian >= startdate && o.danhmucsachdaban.thoigian <= enddate) //tim trong danh sach sach da ban trong khoang thoi gian
                            .AsEnumerable()
                            .Select(c => new chitietdoanhthu(c)).ToList();
                dtvm.doanhthu = tinhdoanhthu(dtvm.ctdt);
                return View(dtvm);
            }
            return View();
        }
        private decimal tinhdoanhthu(List<chitietdoanhthu> ctdt)
        {
            decimal tongdoanhthu = 0;
            foreach (chitietdoanhthu ct in ctdt)
            {
                tongdoanhthu += ct.loinhuan;
            }
            return tongdoanhthu;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebsitePhanPhoiSach/Views/doanhthu/Index.cshtml
@model WebsitePhanPhoiSach.Models.doanhthuviewmodel
@{
    ViewBag.Title = "Index";
}
<h2>Thống kê doanh thu</h2>
@using (Html.BeginForm("Index", "doanhthu", FormMethod.Get))
{
    <div class="form-inline">
        @Html.Label("Từ ngày")
        <div class="form-group input-group-sm">
            @Html.TextBox("tungay", null, new { @class = "form-control datepicker", placeholder = "Enter Drop-off date here...", autocomplete = "off" })
        </div>
        @Html.Label("Đến ngày")
        <div class="form-group input-group-sm">
            @Html.TextBox("denngay", null, new { @class = "form-control datepicker", placeholder = "Enter Drop-off date here...", autocomplete = "off" })
        </div>
        <div class="form-group">
            <div>
                <input type="submit" value="Thống kê" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@if (Model != null)
{
    <table class="table">
        <tr>
            <th>
                Ngày giao dịch
            </th>
            <th>
                Tên sách
            </th>
            <th>
                Số lượng đã bán
            </th>
            <th>
                Thành tiền
            </th>
            <th>
                Số tiền phải trả cho NXB
            </th>
            <th>
                Lợi nhuận
            </th>
        </tr>
        @foreach (var item in Model.ctdt)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ngaygiaodich)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tensach)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.soluongdaban)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.thanhtien)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.sotienphaitrachonxb)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.loinhuan)
                </td>
            </tr>
        }
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>Doanh thu</td>
            <td>@Html.DisplayFor(o => o.doanhthu)</td>
        </tr>
    </table>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/mycustomjquery")
}