WebsitePhanPhoiSach/Models/sotienphaitrachonxb.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsitePhanPhoiSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sotienphaitrachonxb
    {
        public int id { get; set; }
        public Nullable<int> idnxb { get; set; }
        public Nullable<decimal> sotienphaitra { get; set; }
        public Nullable<System.DateTime> thoidiem { get; set; }
    
        public virtual nxb nxb { get; set; }
    }
}

WebsitePhanPhoiSach/Controllers/sotienphaitrachonxbController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebsitePhanPhoiSach.Models;


namespace WebsitePhanPhoiSach.Controllers
{
    public class sotienphaitrachonxbController : Controller
    {
        private ctyppsachEntities db = new ctyppsachEntities();
        // GET: sotienphaitrachonxb
        public ActionResult Index(string thoidiem)
        {
             DateTime searchDate;
            if (DateTime.TryParse(thoidiem, out searchDate))
            {
                
                List<sotienphaitrachonxb> list = new List<sotienphaitrachonxb>();
                DateTime tomorrowdate = searchDate.AddDays(1);
                var sotienphaitrachonxb = db.sotienphaitrachonxbs.Include(b =>b.nxb)
                    .OrderByDescending(o => o.id)
                    .FirstOrDefault(h => h.thoidiem <= tomorrowdate);
                
                list.Add(sotienphaitrachonxb);
               
                return View(list);
                // do not use .Equals() which can not be converted to SQL
            }
        

            var sotienphatrachonxbs = db.sotienphaitrachonxbs.Include(t => t.nxb);
            return View(sotienphatrachonxbs.ToList());
        }
    }
}

WebsitePhanPhoiSach/Views/sotienphaitrachonxb/Index.cshtml
@model IEnumerable<WebsitePhanPhoiSach.Models.sotienphaitrachonxb>
@{
    ViewBag.Title = "Index";
}
<h2>Số tiền phải cho NXB</h2>
@using (Html.BeginForm("Index", "sotienphaitrachonxb", FormMethod.Get))
{
    <div class="form-inline">
        @Html.Label("Thời điểm")
        <div class="form-group input-group-sm">
            @Html.TextBox("thoidiem", null, new { @class = "form-control datepicker", placeholder = "Chọn ngày tháng năm", autocomplete = "off" })
        </div>
        @*<input type="date" class="form-control"/>*@
        <div class="form-group">
            <div>
                <input type="submit" value="Tìm" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<hr />
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Thời điểm cập nhật")
        </th>
        <th>
            @Html.DisplayName("Số lượng tồn")
        </th>
        
        <th>
            @Html.DisplayName("Tên nhà xuất bản")
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.thoidiem)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.sotienphaitra)
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.nxb.tennxb)
            </td>
        </tr>
    }
</table>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/mycustomjquery")
}